spring:
  application:
    name: inbox-app
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 7aacee07bbde35b21ab1
            client-secret: f9150de53e82afe67602e6c4a0831a1cae80f338
  data:
    cassandra:
      keyspace-name: main
      username: qPQtSZBTsHCZqIAaSTFXMWBO
      password: s09O2yM57jrJ4U6fXev,YHWBNPhmN2gQbDKzOf,4f,s+tr4En_K7ppusljQ8nyC23L-JMakREjRzi-8pbHxdNhUOfYlfqtiZyod7EjPIbDEuUTIWPZXyCrTQ8wRAaivn
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

astra.db:
  id: 1f6356f3-f040-45b6-80eb-4d696836a7f3-1
  region: us-east-2
  keyspace: main
  application.token: AstraCS:qPQtSZBTsHCZqIAaSTFXMWBO:e5d8fcbaeffea8b946e64882144649c38960c8f88bc252328734e0aed815fe14

datastax.astra:
  secure-connect-bundle: secure-connect.zip

server:
  port: 18080